In [192]:
DATA_PATH = "../../data/GSE2034_series_matrix.txt"

In [193]:
import pandas as pd

In [194]:
with open(DATA_PATH, "r") as f:
    for i in range(20):
        print(f.readline().strip())

!Series_title	"Breast cancer relapse free survival"
!Series_geo_accession	"GSE2034"
!Series_status	"Public on Feb 23 2005"
!Series_submission_date	"Dec 03 2004"
!Series_last_update_date	"Aug 10 2018"
!Series_pubmed_id	"15721472"
!Series_summary	"This series represents 180 lymph-node negative relapse free patients and 106 lymph-node negate patients that developed a distant metastasis."
!Series_summary	"Please see attached patient clinical parameters sheet for more information."
!Series_summary	"Keywords: other"
!Series_type	"Expression profiling by array"
!Series_sample_id	"GSM36777 GSM36778 GSM36779 GSM36780 GSM36781 GSM36782 GSM36783 GSM36784 GSM36785 GSM36786 GSM36787 GSM36788 GSM36789 GSM36790 GSM36791 GSM36792 GSM36793 GSM36794 GSM36795 GSM36796 GSM36797 GSM36798 GSM36799 GSM36800 GSM36801 GSM36802 GSM36803 GSM36804 GSM36805 GSM36806 GSM36807 GSM36808 GSM36809 GSM36810 GSM36811 GSM36812 GSM36813 GSM36814 GSM36815 GSM36816 GSM36817 GSM36818 GSM36819 GSM36820 GSM36821 GSM36822 GSM36823 GSM36824 GSM36825 GSM36826 GSM36827 GSM36828 GSM36829 GSM36830 GSM36831 GSM36832 GSM36833 GSM36834 GSM36835 GSM36836 GSM36837 GSM36838 GSM36839 GSM36840 GSM36841 GSM36842 GSM36843 GSM36844 GSM36845 GSM36846 GSM36847 GSM36848 GSM36849 GSM36850 GSM36851 GSM36852 GSM36853 GSM36854 GSM36855 GSM36856 GSM36857 GSM36858 GSM36859 GSM36860 GSM36861 GSM36862 GSM36863 GSM36864 GSM36865 GSM36866 GSM36867 GSM36868 GSM36869 GSM36870 GSM36871 GSM36872 GSM36873 GSM36874 GSM36875 GSM36876 GSM36877 GSM36878 GSM36879 GSM36880 GSM36881 GSM36882 GSM36883 GSM36884 GSM36885 GSM36886 GSM36887 GSM36888 GSM36889 GSM36890 GSM36891 GSM36892 GSM36893 GSM36894 GSM36895 GSM36896 GSM36897 GSM36898 GSM36899 GSM36900 GSM36901 GSM36902 GSM36903 GSM36904 GSM36905 GSM36906 GSM36907 GSM36908 GSM36909 GSM36910 GSM36911 GSM36912 GSM36913 GSM36914 GSM36915 GSM36916 GSM36917 GSM36918 GSM36919 GSM36920 GSM36921 GSM36922 GSM36923 GSM36924 GSM36925 GSM36926 GSM36927 GSM36928 GSM36929 GSM36930 GSM36931 GSM36932 GSM36933 GSM36934 GSM36935 GSM36936 GSM36937 GSM36938 GSM36939 GSM36940 GSM36941 GSM36942 GSM36943 GSM36944 GSM36945 GSM36946 GSM36947 GSM36948 GSM36949 GSM36950 GSM36951 GSM36952 GSM36953 GSM36954 GSM36955 GSM36956 GSM36957 GSM36958 GSM36959 GSM36960 GSM36961 GSM36962 GSM36963 GSM36964 GSM36965 GSM36966 GSM36967 GSM36968 GSM36969 GSM36970 GSM36971 GSM36972 GSM36973 GSM36974 GSM36975 GSM36976 GSM36977 GSM36978 GSM36979 GSM36980 GSM36981 GSM36982 GSM36983 GSM36984 GSM36985 GSM36986 GSM36987 GSM36988 GSM36989 GSM36990 GSM36991 GSM36992 GSM36993 GSM36994 GSM36995 GSM36996 GSM36997 GSM36998 GSM36999 GSM37000 GSM37001 GSM37002 GSM37003 GSM37004 GSM37005 GSM37006 GSM37007 GSM37008 GSM37009 GSM37010 GSM37011 GSM37012 GSM37013 GSM37014 GSM37015 GSM37016 GSM37017 GSM37018 GSM37019 GSM37020 GSM37021 GSM37022 GSM37023 GSM37024 GSM37025 GSM37026 GSM37027 GSM37028 GSM37029 GSM37030 GSM37031 GSM37032 GSM37033 GSM37034 GSM37035 GSM37036 GSM37037 GSM37038 GSM37039 GSM37040 GSM37041 GSM37042 GSM37043 GSM37044 GSM37045 GSM37046 GSM37047 GSM37048 GSM37049 GSM37050 GSM37051 GSM37052 GSM37053 GSM37054 GSM37055 GSM37056 GSM37057 GSM37058 GSM37059 GSM37060 GSM37061 GSM37062 "
!Series_contact_name	"Tim,,Jatkoe"
!Series_contact_email	"tjatkoe@vrxus.jnj.com"
!Series_contact_phone	"(858) 320-3315"
!Series_contact_institute	"Veridex"
!Series_contact_address	" "
!Series_contact_city	"San Diego"
!Series_contact_state	"CA"
!Series_contact_zip/postal_code	"92121"
!Series_contact_country	"USA"

In [195]:
with open(DATA_PATH, "r") as f:
    for i, line in enumerate(f):
        if line.startswith("\"ID_REF\""):
            print(f"Expression matrix starts at line {i}")
            break

Expression matrix starts at line 54

In [196]:
dfe = pd.read_csv(
    DATA_PATH,
    sep="\t",
    skiprows=54
)

print(dfe.shape)

(22284, 287)

In [197]:
print(dfe.iloc[:5, :6])

      ID_REF  GSM36777  GSM36778  GSM36779  GSM36780  GSM36781
0  1007_s_at    3848.1    6520.9    5285.7    4043.7    4263.6
1    1053_at     228.9     112.5     178.4     398.7     417.7
2     117_at     213.1     189.8     269.7     312.4     327.1
3     121_at    1009.4    2083.3    1203.4    1104.4    1043.3
4  1255_g_at      31.8     145.8      42.5     108.2      69.2

In [198]:
dfe = dfe.set_index("ID_REF")

In [199]:
dfe.head()

,GSM36777,GSM36778,GSM36779,GSM36780,GSM36781,GSM36782,GSM36783,GSM36784,GSM36785,GSM36786,...,GSM37053,GSM37054,GSM37055,GSM37056,GSM37057,GSM37058,GSM37059,GSM37060,GSM37061,GSM37062
ID_REF,,,,,,,,,,,,,,,,,,,,,
1007_s_at,3848.1,6520.9,5285.7,4043.7,4263.6,2949.8,5498.9,3863.1,3370.4,3991.9,...,4058.2,4017.6,2841.0,2914.2,3681.0,3066.9,2773.0,2984.3,3540.0,2620.0
1053_at,228.9,112.5,178.4,398.7,417.7,221.2,280.4,198.2,304.7,198.2,...,183.4,356.1,234.6,169.4,94.5,265.5,209.8,160.0,285.7,180.5
117_at,213.1,189.8,269.7,312.4,327.1,225.0,243.5,244.4,348.5,185.3,...,326.6,234.9,369.6,149.5,236.4,347.9,226.7,252.9,135.1,191.8
121_at,1009.4,2083.3,1203.4,1104.4,1043.3,1117.6,1085.4,1423.1,1196.4,993.3,...,1041.3,1195.6,751.5,1117.8,1022.4,1127.4,1071.8,1178.5,1256.7,1284.6
1255_g_at,31.8,145.8,42.5,108.2,69.2,47.4,84.3,102.0,22.8,86.3,...,143.5,32.7,62.6,43.0,100.5,47.0,45.1,146.3,75.9,87.4

In [200]:
DATA_PATH_CL = "../../data/GSE2034_clinical.txt"

In [201]:
with open(DATA_PATH_CL, "r") as f:
    for i in range(20):
        print(f.readline().strip())

#PID =
#GEO asscession number =
#lymph node status =
#time to relapse or last follow-up (months) =
#relapse (1=True) =
#ER Status =
#Brain relapses (1=yes, 0=no) =
PID	GEO_asscession_number	lymph_node_status	time_to_relapse	relapse	ER_Status	Brain_relapses
3	GSM36793	negative	101	0	ER-	0
5	GSM36796	negative	118	0	ER+	0
6	GSM36797	negative	9	1	ER-	0
7	GSM36798	negative	106	0	ER-	0
8	GSM36800	negative	37	1	ER-	0
9	GSM36801	negative	125	0	ER+	0
11	GSM36834	negative	109	0	ER+	0
14	GSM36835	negative	14	1	ER-	0
15	GSM36836	negative	99	0	ER+	0
17	GSM36837	negative	137	0	ER+	0
18	GSM36838	negative	34	1	ER+	0
19	GSM36839	negative	32	1	ER+	0

In [202]:
with open(DATA_PATH_CL, "r") as f:
    for i, line in enumerate(f):
        if line.startswith("PID"):
            print(f"Expression matrix starts at line {i}")
            break

Expression matrix starts at line 7

In [203]:
dfc = pd.read_csv(
    DATA_PATH_CL,
    sep="\t",
    skiprows=7
)

print(dfc.shape)

(286, 7)

In [204]:
dfc = dfc.rename(columns={
    "GEO_asscession_number": "GEO_accession_number"
})
dfc.head()

,PID,GEO_accession_number,lymph_node_status,time_to_relapse,relapse,ER_Status,Brain_relapses
0,3,GSM36793,negative,101,0,ER-,0
1,5,GSM36796,negative,118,0,ER+,0
2,6,GSM36797,negative,9,1,ER-,0
3,7,GSM36798,negative,106,0,ER-,0
4,8,GSM36800,negative,37,1,ER-,0

In [205]:
dfc = dfc.drop('PID', axis=1)

In [206]:
dfc.head()

,GEO_accession_number,lymph_node_status,time_to_relapse,relapse,ER_Status,Brain_relapses
0,GSM36793,negative,101,0,ER-,0
1,GSM36796,negative,118,0,ER+,0
2,GSM36797,negative,9,1,ER-,0
3,GSM36798,negative,106,0,ER-,0
4,GSM36800,negative,37,1,ER-,0

In [216]:
print(dfe.info())

<class 'pandas.core.frame.DataFrame'>
Index: 286 entries, GSM36777 to GSM37062
Columns: 22284 entries, 1007_s_at to !series_matrix_table_end
dtypes: float64(22284)
memory usage: 48.6+ MB
None

In [217]:
dfe = dfe.drop(["!series_matrix_table_end"], axis=1)

In [215]:
print(dfc.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 286 entries, 0 to 285
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   GEO_accession_number  286 non-null    object
 1   lymph_node_status     286 non-null    object
 2   time_to_relapse       286 non-null    int64
 3   relapse               286 non-null    int64
 4   ER_Status             286 non-null    object
 5   Brain_relapses        286 non-null    int64
dtypes: int64(3), object(3)
memory usage: 13.5+ KB
None

In [207]:
dfe_patients = set(dfe.columns)
dfc_patients = set(dfc["GEO_accession_number"])

print(len(dfe_patients))
print(len(dfc_patients))
print(len(dfe_patients & dfc_patients))

286
286
286

In [208]:
dfe.index.name = "GEO_accession_number"
dfe = dfe.T
dfe.head()

GEO_accession_number,1007_s_at,1053_at,117_at,121_at,1255_g_at,1294_at,1316_at,1320_at,1405_i_at,1431_at,...,AFFX-r2-Hs28SrRNA-M_at,AFFX-r2-P1-cre-3_at,AFFX-r2-P1-cre-5_at,AFFX-ThrX-3_at,AFFX-ThrX-5_at,AFFX-ThrX-M_at,AFFX-TrpnX-3_at,AFFX-TrpnX-5_at,AFFX-TrpnX-M_at,!series_matrix_table_end
GSM36777,3848.1,228.9,213.1,1009.4,31.8,551.5,176.7,11.9,309.3,49.9,...,661.5,33168.9,25644.4,11.1,9.2,25.0,4.2,7.0,10.0,NaN
GSM36778,6520.9,112.5,189.8,2083.3,145.8,802.8,278.4,28.3,449.0,122.9,...,716.1,54401.4,40720.0,17.1,62.0,21.4,9.3,11.2,15.7,NaN
GSM36779,5285.7,178.4,269.7,1203.4,42.5,557.5,183.3,56.4,101.9,85.9,...,1189.3,61244.1,50878.7,6.4,8.4,7.4,7.1,64.0,4.1,NaN
GSM36780,4043.7,398.7,312.4,1104.4,108.2,568.5,187.7,42.1,899.1,90.7,...,801.1,62292.1,46870.8,13.5,10.8,16.0,4.6,12.2,7.3,NaN
GSM36781,4263.6,417.7,327.1,1043.3,69.2,653.2,185.8,21.8,3629.3,96.0,...,191.1,57295.1,40847.1,19.8,30.5,22.1,7.3,5.5,11.6,NaN

In [219]:
print("Missing count expr",dfe.isnull().sum().sum())
print("Missing count clinical",dfc.isnull().sum().sum())
print("Expression matrix:", dfe.shape)
print("Clinical data:", dfc.shape)

Missing count expr 0
Missing count clinical 0
Expression matrix: (286, 22283)
Clinical data: (286, 6)

In [209]:
data = dfe.merge(
    dfc,
    left_index=True,
    right_on="GEO_accession_number"
)

In [ ]:
data.head()

,1007_s_at,1053_at,117_at,121_at,1255_g_at,1294_at,1316_at,1320_at,1405_i_at,1431_at,...,AFFX-ThrX-M_at,AFFX-TrpnX-3_at,AFFX-TrpnX-5_at,AFFX-TrpnX-M_at,GEO_accession_number,lymph_node_status,time_to_relapse,relapse,ER_Status,Brain_relapses
145,3848.1,228.9,213.1,1009.4,31.8,551.5,176.7,11.9,309.3,49.9,...,25.0,4.2,7.0,10.0,GSM36777,negative,79,0,ER+,0
146,6520.9,112.5,189.8,2083.3,145.8,802.8,278.4,28.3,449.0,122.9,...,21.4,9.3,11.2,15.7,GSM36778,negative,50,1,ER+,0
232,5285.7,178.4,269.7,1203.4,42.5,557.5,183.3,56.4,101.9,85.9,...,7.4,7.1,64.0,4.1,GSM36779,negative,132,0,ER+,0
250,4043.7,398.7,312.4,1104.4,108.2,568.5,187.7,42.1,899.1,90.7,...,16.0,4.6,12.2,7.3,GSM36780,negative,84,0,ER-,0
211,4263.6,417.7,327.1,1043.3,69.2,653.2,185.8,21.8,3629.3,96.0,...,22.1,7.3,5.5,11.6,GSM36781,negative,147,0,ER+,0

In [213]:
data.set_index("GEO_accession_number")

,1007_s_at,1053_at,117_at,121_at,1255_g_at,1294_at,1316_at,1320_at,1405_i_at,1431_at,...,AFFX-ThrX-5_at,AFFX-ThrX-M_at,AFFX-TrpnX-3_at,AFFX-TrpnX-5_at,AFFX-TrpnX-M_at,lymph_node_status,time_to_relapse,relapse,ER_Status,Brain_relapses
GEO_accession_number,,,,,,,,,,,,,,,,,,,,,
GSM36777,3848.1,228.9,213.1,1009.4,31.8,551.5,176.7,11.9,309.3,49.9,...,9.2,25.0,4.2,7.0,10.0,negative,79,0,ER+,0
GSM36778,6520.9,112.5,189.8,2083.3,145.8,802.8,278.4,28.3,449.0,122.9,...,62.0,21.4,9.3,11.2,15.7,negative,50,1,ER+,0
GSM36779,5285.7,178.4,269.7,1203.4,42.5,557.5,183.3,56.4,101.9,85.9,...,8.4,7.4,7.1,64.0,4.1,negative,132,0,ER+,0
GSM36780,4043.7,398.7,312.4,1104.4,108.2,568.5,187.7,42.1,899.1,90.7,...,10.8,16.0,4.6,12.2,7.3,negative,84,0,ER-,0
GSM36781,4263.6,417.7,327.1,1043.3,69.2,653.2,185.8,21.8,3629.3,96.0,...,30.5,22.1,7.3,5.5,11.6,negative,147,0,ER+,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
GSM37058,3066.9,265.5,347.9,1127.4,47.0,583.9,138.2,16.1,577.3,44.7,...,13.8,28.8,6.6,32.1,5.4,negative,64,1,ER+,0
GSM37059,2773.0,209.8,226.7,1071.8,45.1,859.9,121.0,24.8,935.6,78.8,...,72.3,66.2,17.8,33.1,3.7,negative,83,0,ER+,0
GSM37060,2984.3,160.0,252.9,1178.5,146.3,664.2,183.3,49.6,443.5,74.0,...,26.8,18.0,7.1,29.5,10.7,negative,81,0,ER+,0
GSM37061,3540.0,285.7,135.1,1256.7,75.9,603.1,125.0,72.9,73.5,126.1,...,11.7,26.4,20.4,14.5,4.0,negative,105,0,ER-,0
GSM37062,2620.0,180.5,191.8,1284.6,87.4,316.2,177.0,80.4,334.9,118.8,...,10.0,61.9,23.7,11.9,8.9,negative,54,0,ER+,0

In [220]:
DATA_PATH_SAVE = "../../data/final/"

In [221]:
dfe.to_csv(f"{DATA_PATH_SAVE}/expression_matrix.csv", index=False)
dfc.to_csv(f"{DATA_PATH_SAVE}/clinical_data.csv", index=False)
data.to_csv(f"{DATA_PATH_SAVE}/final_data.csv", index=False)